export const WORD_LIST = new Set(["ace","act","add","age","ago","aid","aim","air","all","and","ant","ape","apt","arc","are","ark","arm","art","ash","ask","axe",
  "bad","bag","ban","bar","bat","bay","bed","big","bit","bow","box","boy","bun","bus","but","buy",
  "cab","can","cap","car","cat","cob","cod","cop","cot","cow","cry","cup","cut",
  "dam","day","den","dew","did","dig","dim","dip","dog","dot","dry","due","dug","dye",
  "ear","eat","egg","ego","elf","elm","end","era","eve","ewe","eye",
  "fad","fan","far","fat","fax","fed","few","fig","fin","fit","fix","fly","fog","foe","for","fox","fry","fun","fur",
  "gap","gas","get","gig","gin","gnu","god","got","gun","gut","guy",
  "had","ham","has","hat","hay","hen","her","hid","him","hip","his","hit","hog","hop","hot","how","hub","hug","hum","hut",
  "ice","ill","imp","ink","inn","ion","ire",
  "jab","jag","jam","jar","jaw","jet","jot","joy","jug","jut",
  "keg","key","kid","kin","kit",
  "lab","lap","law","lay","led","leg","let","lid","lie","lip","lit","log","lot","low",
  "mad","man","map","mat","men","met","mix","mob","mop","mud","mug","nab","nag","nap","net","new","nil","nip","nod","nor","not","now","nun","nut",
  "oak","oar","odd","ode","off","oil","old","one","opt","orb","ore","our","out","owe","owl","own",
  "pad","pal","pan","paw","pay","pea","peg","pen","pet","pie","pig","pit","ply","pod","pop","pot","pow","pro","pub","pun","pup","put",
  "ram","ran","rat","raw","ray","red","rep","rid","rig","rip","rob","rod","rot","row","rub","rug","run","rut",
  "sad","sag","sap","sat","saw","say","sea","set","sew","she","shy","sin","sip","sit","six","ski","sky","sly","sob","sod","son","sow","soy","spa","spy","sty","sub","sum","sun","sup",
  "tab","tan","tap","tar","tea","the","tie","tin","tip","toe","too","top","tow","toy","try","tub","tug","two",
  "urn","use","van","vat","vet","vow","wag","war","was","wax","web","wed","wig","win","wit","woe","wok","won","woo","wow",
  "yam","yap","yew","yore","you",
  "zap","zen","zip","zoo",
  // 4-letter
  "able","ache","acid","acre","aged","ages","aids","aims","airs","akin","alma","also","alto","alum","amen","amid","amok","amok","amps","ankh","ante","apex","arch","area","aria","arid","army","arty","atom","aunt","auto","avid","away","awed","axle","azure",
  "back","bade","bail","bait","bake","bald","bale","balk","ball","balm","band","bane","bang","bank","bare","bark","barn","base","bash","bask","bass","beak","beam","bean","bear","beat","been","beef","beer","beet","bell","belt","bend","bent","best","bill","bind","bird","bite","blab","blah","blip","blob","bloc","blog","blot","blow","blue","blur","boar","boat","body","bold","bolt","bond","bone","book","boom","boot","bore","born","both","bout","brag","bran","brat","bray","brew","brim","brow","buck","bulb","bulk","bull","bump","burn","burp","burr","bush","buzz",
  "cage","cake","call","calm","came","cane","cape","card","care","cart","case","cash","cast","cave","cell","chap","char","chat","chef","chew","chin","chip","chop","cite","clam","clap","claw","clay","clip","clog","clot","club","clue","coal","coat","coil","coin","cola","cold","coma","come","cone","cook","cool","coop","cope","cord","core","cork","corn","cost","cozy","crag","cram","crap","crew","crop","crow","crud","cube","curb","cure","curl","cyst",
  "dale","dare","dark","dart","data","date","dawn","dead","deal","dear","deck","deed","deep","deer","deny","desk","dew","dial","dice","died","dike","dime","dine","dire","dirt","disk","dive","dock","dome","done","dope","dork","dose","dove","down","drag","draw","drew","drip","drop","drug","drum","dual","duel","dumb","dump","dunk","dusk","dust","duty",
  "each","earn","ease","east","easy","edge","edit","eels","emit","envy","epic","even","ever","evil","exam",
  "face","fact","fade","fail","fair","fake","fall","fame","fang","farm","fate","faze","fear","feat","feed","feel","feet","fell","felt","fend","fern","feud","fief","file","fill","film","find","fine","fire","firm","fish","fist","five","flag","flak","flap","flat","flaw","flea","flew","flex","flip","flit","flog","flop","flow","foam","fold","folk","fond","font","food","fool","foot","ford","fore","fork","form","fort","foul","four","fowl","fray","free","fret","frog","from","fuel","full","fume","fund","funk","furl","fury","fuse","fuzz",
  "gain","gale","gall","game","gang","gate","gaze","gear","germ","gift","gill","girl","give","glad","glee","glib","glob","glue","glum","gnat","goal","goat","goes","gold","golf","gone","good","gory","gown","grab","grit","grow","grub","gruel","gulf","gull","gush","gust","guts",
  "hack","hail","hair","hale","half","hall","halt","hand","hang","hard","hare","hark","harm","harp","hash","hate","haul","head","heal","heap","hear","heat","heel","held","helm","help","herb","herd","here","hero","hide","high","hike","hill","hire","hive","hoax","hold","hole","home","hone","hoof","hook","hope","horn","hose","hour","huff","hulk","hull","hung","hunt","hurt","husk","hymn",
  "idea","idle","idol","imam","inch","info","into","iron","isle",
  "jail","jest","join","joke","jolt","junk","jury","just",
  "keen","keep","kick","kill","kind","king","kiss","knit","knob","knot","know",
  "lack","lake","lame","lamp","land","lane","lard","lash","laud","lava","lawn","lead","leaf","leak","lean","leap","lend","lens","lest","levy","liar","lick","lift","like","lily","lime","line","link","lion","list","live","load","lobe","lock","loft","lone","long","look","loom","loon","lore","lore","lore","lost","loud","lout","love","luck","lull","lump","lung","lurk","lust","lute",
  "mace","made","mail","main","make","male","mall","malt","mane","mare","mark","mars","mash","mast","mate","math","maze","mead","meal","mean","meat","melt","memo","mend","mere","mesa","mesh","mild","mile","mill","mime","mind","mine","mint","mire","miss","mist","moat","mode","mole","molt","monk","moon","moot","more","moss","most","moth","move","much","muck","mule","muse","mute",
  "nail","name","nape","navy","near","neat","neck","need","news","nice","nigh","nine","node","none","noon","nope","norm","nose","note","null",
  "oboe","once","only","open","opus","orca","oven","over","oxen",
  "pace","pack","page","pain","pair","pale","palm","park","part","pass","past","path","pave","peak","peal","peck","peek","peel","peer","pelt","perm","pick","pile","pine","pink","pipe","pity","pixe","plan","play","plea","plod","plot","plow","ploy","ploy","plug","plum","plop","poem","poet","poke","pole","poll","pomp","pond","pool","poor","pope","pork","port","pose","post","pour","pray","prey","prim","prod","prop","puck","pull","pump","pure","push",
  "rack","rage","raid","rail","rain","rake","ramp","rang","rank","rant","rapt","rash","rasp","rate","rave","read","real","reap","reel","rein","rely","rend","rend","rent","rest","rice","rich","ride","rile","rind","ring","riot","ripe","rise","risk","road","roam","roar","robe","role","roll","roof","rook","root","rope","rose","rote","rove","ruin","rule","ruse","rush","rust",
  "sack","sage","sail","sake","sale","salt","same","sand","sane","sang","sash","save","scan","scar","seal","seam","sect","seed","seek","seem","seep","seer","self","sell","send","sent","shed","shin","ship","shop","shot","show","sick","side","sift","sigh","silk","sill","silo","silt","sing","sink","site","size","skid","skin","skip","slab","slam","slap","slat","sled","slew","slid","slim","slip","slit","slob","slop","slot","slow","slug","slum","slur","smog","snag","snap","snip","snob","snug","soak","soap","soar","sock","soft","soil","sole","some","song","sort","soul","sour","span","spar","spin","spit","spud","spur","stab","star","stay","stem","step","stew","stir","stop","stub","such","suit","sulk","surf","swam","swap","swat","sway","swim","swum",
  "tack","tale","talk","tall","tame","tank","tape","tare","taut","taxi","tear","tech","tell","tend","tent","term","test","text","than","that","them","then","thin","this","thorn","tick","tile","till","tilt","time","tiny","tire","toad","toil","told","toll","tomb","tome","tone","tong","tool","tore","torn","toss","tour","town","tram","trap","trek","trim","trip","trod","trot","true","tube","tuck","tuft","tuna","tune","turf","turn","tusk","tutu","type",
  "ugly","undo","unit","upon","urge",
  "vale","vane","vary","veil","vein","very","vest","vibe","vice","vile","vine","vise","void","volt","vote",
  "wade","wage","wake","wand","want","ward","warm","warn","wart","wave","weak","weal","wean","weld","well","welt","wend","went","west","what","when","whim","whip","wick","wide","wife","wild","will","wilt","wind","wine","wing","wink","wire","wise","wish","with","woke","wolf","womb","wood","wool","word","wore","work","worm","worn","wove","wrap","wren","writ",
  "yell","yoga","yolk","yore","york","yuan","yule",
  "zeal","zero","zest","zinc","zone",
  // 5-letter
  "about","above","abuse","actor","acute","admit","adopt","adult","after","again","agile","aging","agree","ahead","alarm","album","alert","alike","align","alive","alley","allot","allow","alone","along","aloof","alpha","altar","alter","amber","among","angel","anger","angle","angry","ankle","annex","annoy","antic","aorta","apart","apply","apron","arbor","ardor","arise","armor","aroma","arose","array","arson","atlas","atone","attic","audit","augur","avoid","awake","awash","axial",
  "baker","banjo","basic","basin","basis","batch","began","begin","below","bench","black","blade","blame","bland","blank","blast","blaze","bleak","bleed","blend","bless","blight","blind","block","blood","bloom","blown","blunt","board","boast","boxer","braid","brake","brand","brave","brawl","break","bride","brief","bring","brink","broad","broke","brood","brook","broom","brown","brush","build","built","bulge","buyer",
  "cable","cadet","camel","canal","candy","cargo","carry","catch","cause","cease","chain","chair","chalk","champ","chaos","charm","chase","cheap","check","cheek","chess","chest","chief","child","choir","chore","chose","civic","civil","claim","clash","class","clean","clear","clerk","click","cliff","climb","cling","clock","close","cloth","cloud","coach","coast","cobra","comet","comic","comma","coral","cords","could","count","court","cover","crack","craft","crane","cramp","craze","creak","creek","crest","crime","crimp","crisp","cross","crowd","crown","crush","crypt","curry","curve","cycle",
  "daily","dairy","dance","datum","death","debut","decoy","delta","depot","depth","derby","devil","digit","diner","disco","ditch","dizzy","dodge","doing","donor","doubt","dough","draft","drain","drama","drape","drash","drawn","dread","dream","dried","drift","drink","drive","drone","drove","dwarf","dwell",
  "eager","eagle","early","earth","eight","elite","email","ember","empty","ended","enemy","enjoy","enter","entry","equal","equip","error","essay","event","every","exact","excel","extra","exert","exude",
  "fable","facet","faith","false","fancy","favor","feast","ferry","fever","fiber","fiend","fifty","fight","final","first","fjord","flame","flask","flick","floor","flour","focus","force","forge","found","frame","franc","frank","fraud","fresh","front","frost","froth","frown","froze","fully","fungi","funky",
  "gleam","glide","glint","globe","gloom","gloss","glove","glyph","gnash","grace","grade","grain","grand","grant","grasp","grass","grave","graze","greed","green","greet","grief","grime","grind","groan","groin","groom","grope","gross","group","grove","growl","gruel","guard","guest","guide","guile","guise","gusto","gypsy",
  "habit","happy","harsh","haven","hazel","heart","heavy","hedge","heist","hence","heron","hinge","hippo","hoist","holly","honey","honor","horse","hotel","hound","house","human","humid","humor","hurry",
  "image","imply","inbox","incur","index","indie","infer","ingot","input","inter","intro",
  "irony","issue","ivory",
  "jaunt","jewel","judge","juice","juicy","juror",
  "karma","ketch","knack","knife","knock","known",
  "label","lance","large","laser","latch","later","laugh","layer","learn","leash","least","leave","light","limit","liner","lingo","liver","llama","logic","lorry","lover","lower","lucky","lusty","lyric",
  "magic","major","maker","manor","marble","march","match","mayor","media","mercy","merit","metal","minor","minus","mimic","modem","money","month","moose","moral","mourn","mouse","mouth","music","myrrh","mystery",
  "naive","never","night","ninja","nod","noise","north","noter","novel","nurse",
  "oasis","occur","offer","often","olive","onset","opera","orbit","order","other","outer","outdo","oxide",
  "pagan","paint","panel","panic","pasta","patch","pause","peace","pearl","pedal","penny","perch","petal","phase","phone","photo","piano","pinch","pixel","pizza","place","plain","plane","plant","plate","plaza","plead","pluck","plume","plunge","point","poise","poker","polar","prank","press","price","pride","prime","prince","print","prior","prize","probe","prone","proof","proud","prove","prowl","prune","pulse","punch","purse","queen","quest","queue","quick","quiet","quirk","quota","quote",
  "racer","radar","radio","raise","rally","ranch","range","rapid","ratio","rayon","reach","react","rebel","recur","reign","relax","relic","repay","resin","retro","rider","risky","rival","river","robot","rocky","rouge","rough","roost","round","route","rover","royal","rugby","ruler","rupee","rural",
  "salad","sauce","scale","scene","scout","scram","scrub","seize","serve","seven","shade","shake","shame","shape","share","shark","sharp","sheet","shelf","shift","shirt","shone","shore","shout","shove","shrug","sight","silly","since","sixty","skill","skull","slate","slave","sleek","sleep","sleet","slender","slice","slide","slope","slosh","small","smart","smell","smile","smirk","smoke","smote","smug","snake","snail","snare","sneak","snore","solid","sonic","sorry","south","space","spare","spark","spawn","speak","spear","speed","spend","spice","spike","spill","spine","spite","spoil","spoke","spook","spoon","squad","squat","stale","stall","stamp","stand","stash","state","steal","steel","steep","steer","stern","stick","sting","stone","stood","stool","storm","story","stout","shove","straw","stray","strip","strut","study","stuff","stump","stung","style","sugar","super","swear","sweep","sweet","swept","swift","swore","sword","swore",
  "table","talon","taste","teach","teeth","tempo","tense","theme","there","these","thick","thigh","thing","think","thorn","those","three","threw","throw","thumb","tiger","tiger","title","today","touch","tough","tower","toxic","trace","track","trade","trail","train","trait","trash","treat","trial","trick","tried","troop","troth","trove","truck","truly","trump","trunk","tuner","twist","tying",
  "umbra","uncle","under","union","unity","until","unzip","uplift","upset","urban","usage","usual","utmost","utter",
  "vague","valid","valor","value","valve","verse","vibrant","video","vigor","viral","visor","vista","vital","vivid","vocal","vogue","voice","voodoo","voter",
  "wager","watch","water","weary","weave","wedge","weigh","weird","whale","wheat","where","while","whirl","white","whole","whose","wider","wield","witch","woman","women","world","worse","worth","would","wound","wring","wrote","wrath",
  "yacht","yearn","yield","young","youth",
  "zebra","zonal"]);

export const THEMES = [
  { name: "OCEAN LIFE", words: ["sea","wave","tide","fish","crab","reef","kelp","foam","dive","boat","sail","whale","shark","coral","orca","brine","coil","net"] },
  { name: "PREDATORS", words: ["wolf","fang","claw","bite","hunt","trap","prey","snarl","lure","stalk","kill","lurk","bear","lion","hawk","puma","venom"] },
  { name: "TECHNOLOGY", words: ["code","data","byte","hack","node","wire","chip","grid","boot","ping","log","pixel","binary","core","loop","ram","net","patch"] },
  { name: "WEATHER", words: ["rain","snow","hail","wind","gale","sleet","fog","mist","cloud","bolt","storm","frost","ice","damp","gust","chill","dew","humid"] },
  { name: "DARK MAGIC", words: ["hex","rune","curse","void","soul","doom","omen","sigil","seal","bind","tomb","wrath","dread","smite","ash","sorrow","ghost","shade"] },
  { name: "FOOD & FEAST", words: ["loaf","salt","herb","cook","meat","stew","broth","spice","bake","brew","grain","flour","honey","sauce","crisp","corn","bean","yam"] },
  { name: "SPACE", words: ["star","moon","sun","void","comet","orbit","dust","ring","nova","fuel","drift","core","ion","probe","dark","mass","warp","pulsar"] },
  { name: "URBAN JUNGLE", words: ["road","alley","smog","block","light","wall","gate","sign","lane","curb","grid","pipe","drain","roof","lock","cable","mall","pole"] },
  { name: "THE BODY", words: ["bone","vein","lung","arm","leg","skin","nerve","pulse","cell","chest","jaw","knee","palm","heel","calf","shin","back","rib"] },
  { name: "CYBER GLITCH", words: ["lag","bug","loop","null","void","data","glitch","trace","scan","probe","hack","fuse","wipe","burn","boot","drift","echo","ping"] }
];
